"""initial schema

Revision ID: ecbe5615243f
Revises: 
Create Date: 2026-08-18 07:45:59.971383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecbe5615243f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('behaviour_metrics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_type', sa.Enum('FORGOTTEN_TASK_RATE', 'AVG_INTERRUPTIONS_PER_SESSION', 'CONTEXT_SWITCH_COUNT', 'FOCUS_MINUTES', 'TASK_COMPLETION_RATE', 'AVG_TASK_DELAY_MINUTES', name='behaviour_metric_type'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('metric_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'metric_date', 'metric_type', name='uq_behaviour_metric_per_day')
    )
    op.create_index(op.f('ix_behaviour_metrics_metric_date'), 'behaviour_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_behaviour_metrics_metric_type'), 'behaviour_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_behaviour_metrics_user_id'), 'behaviour_metrics', ['user_id'], unique=False)
    op.create_table('locations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location_type', sa.Enum('HOME', 'WORK', 'GYM', 'COMMUTE', 'STUDY', 'OTHER', name='location_type'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_meters', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_user_id'), 'locations', ['user_id'], unique=False)
    op.create_table('context_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('context_tag', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_count', sa.Integer(), nullable=False),
    sa.Column('interruption_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_sessions_context_tag'), 'context_sessions', ['context_tag'], unique=False)
    op.create_index(op.f('ix_context_sessions_started_at'), 'context_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_context_sessions_user_id'), 'context_sessions', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'FORGOTTEN', 'CANCELLED', name='task_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='task_priority'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context_location_id', sa.UUID(), nullable=True),
    sa.Column('context_tag', sa.String(length=64), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=255), nullable=True),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_context_location_id'), 'tasks', ['context_location_id'], unique=False)
    op.create_index(op.f('ix_tasks_context_tag'), 'tasks', ['context_tag'], unique=False)
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('interruptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('interruption_type', sa.Enum('PHONE', 'SOCIAL_MEDIA', 'MESSAGE', 'CALL', 'SEARCH', 'PERSON', 'FOOD', 'OTHER', name='interruption_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interruptions_interruption_type'), 'interruptions', ['interruption_type'], unique=False)
    op.create_index(op.f('ix_interruptions_occurred_at'), 'interruptions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_interruptions_task_id'), 'interruptions', ['task_id'], unique=False)
    op.create_index(op.f('ix_interruptions_user_id'), 'interruptions', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('prediction_type', sa.Enum('FORGET_RISK', 'OPTIMAL_TIME_WINDOW', 'CONTEXT_SWITCH_RISK', 'INTERRUPTION_RISK', 'ONE_MORE_THING', name='prediction_type'), nullable=False),
    sa.Column('predicted_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_prediction_type'), 'predictions', ['prediction_type'], unique=False)
    op.create_index(op.f('ix_predictions_task_id'), 'predictions', ['task_id'], unique=False)
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_type', sa.Enum('REMINDER', 'SCHEDULE_SHIFT', 'BATCH_TASKS', 'LOCATION_TRIGGER', 'BREAK_SUGGESTION', 'ONE_MORE_THING_NUDGE', name='recommendation_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SHOWN', 'ACCEPTED', 'DISMISSED', 'EXPIRED', name='recommendation_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_task_id'), 'recommendations', ['task_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('task_associations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('associated_task_id', sa.UUID(), nullable=False),
    sa.Column('association_type', sa.Enum('OFTEN_FORGOTTEN_WITH', 'SEQUENTIAL', 'BLOCKS', 'CONTEXT_LINKED', name='association_type'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('support', sa.Float(), nullable=True),
    sa.Column('lift', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['associated_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_associations_associated_task_id'), 'task_associations', ['associated_task_id'], unique=False)
    op.create_index(op.f('ix_task_associations_task_id'), 'task_associations', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_associations_user_id'), 'task_associations', ['user_id'], unique=False)
    op.create_table('task_events',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'STARTED', 'PAUSED', 'RESUMED', 'COMPLETED', 'FORGOTTEN', 'CANCELLED', name='task_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_event_type'), 'task_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_task_events_occurred_at'), 'task_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_events_user_id'), 'task_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_events_user_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_occurred_at'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_event_type'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_task_associations_user_id'), table_name='task_associations')
    op.drop_index(op.f('ix_task_associations_task_id'), table_name='task_associations')
    op.drop_index(op.f('ix_task_associations_associated_task_id'), table_name='task_associations')
    op.drop_table('task_associations')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_task_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_task_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_prediction_type'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_interruptions_user_id'), table_name='interruptions')
    op.drop_index(op.f('ix_interruptions_task_id'), table_name='interruptions')
    op.drop_index(op.f('ix_interruptions_occurred_at'), table_name='interruptions')
    op.drop_index(op.f('ix_interruptions_interruption_type'), table_name='interruptions')
    op.drop_table('interruptions')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_context_tag'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_context_location_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_context_sessions_user_id'), table_name='context_sessions')
    op.drop_index(op.f('ix_context_sessions_started_at'), table_name='context_sessions')
    op.drop_index(op.f('ix_context_sessions_context_tag'), table_name='context_sessions')
    op.drop_table('context_sessions')
    op.drop_index(op.f('ix_locations_user_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_behaviour_metrics_user_id'), table_name='behaviour_metrics')
    op.drop_index(op.f('ix_behaviour_metrics_metric_type'), table_name='behaviour_metrics')
    op.drop_index(op.f('ix_behaviour_metrics_metric_date'), table_name='behaviour_metrics')
    op.drop_table('behaviour_metrics')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
